In [2]:
import os
import pandas as pd

In [3]:
# (1)Patients, which contains static information about the patients, such as gender, date of birth, and date of death; 
# (2)Admissions, which holdsinformation about patient admissions to the hospital, including admissionand discharge times, as well as information related to the hospital stay; 
# (3)Icustays, which is specifically related to intensive care unit (ICU) stays,including the timings and type of ICU; 
# (4)Labevents, which containslaboratory test results for patients. We used the 200 most frequent testscovering 95% of tests completed; 
# (5)Prescriptions, which holds informationon medications prescribed to patients during their stay, with each drugconverted to ATC code33We converted GSN codes in MIMIC-IV to ATCcodes using conversion tables26;
# (6)Procedures which contains informationabout procedures performed on patients, codedusing ICD10-PCS codes; 
# (7)Diagnoses which contains diagnostic information, typically coded using ICD10-CM codes. We converted ICD9 to ICD10-CM if needed usingconversion table34;
# (8)Emar, which holds information related to the documentation and administration of medications to patients; 
# (9)Omr with information about measurements taken from a patient, such as blood pressure or BMI; 
# (10)Services with information about the clinical service under which a patient is managed during their hospital stay; 
# (11)drgcodesDRG codes which are a classification system used in the healthcare industry to categorize hospital cases into groups that are expected to have similarhospital resource use; 
# (12) SOFA, taken from the derived tables in MIMIC.

In [4]:
os.listdir('/scratch/fs999/shamoutlab/data/physionet.org/files/mimic-iv-1.0/icu/')

['inputevents.csv',
 'icustays.csv',
 'd_items.csv',
 'datetimeevents.csv',
 'procedureevents.csv',
 'outputevents.csv',
 'chartevents.csv']

In [34]:
# patients = pd.read_csv('/scratch/fs999/shamoutlab/data/physionet.org/files/mimic-iv-1.0/core/patients.csv')
# admission = pd.read_csv('/scratch/fs999/shamoutlab/data/physionet.org/files/mimic-iv-1.0/core/admissions.csv')
# transfers = pd.read_csv('/scratch/fs999/shamoutlab/data/physionet.org/files/mimic-iv-1.0/core/transfers.csv')
chart = pd.read_csv()

/tmpdata/ipykernel_1092201/433388495.py:4: DtypeWarning: Columns (7,9,12) have mixed types. Specify dtype option on import or set low_memory=False.
  labs = pd.read_csv('/scratch/fs999/shamoutlab/data/physionet.org/files/mimic-iv-1.0/hosp/labevents.csv')

In [39]:
labs = pd.read_csv('/scratch/fs999/shamoutlab/data/physionet.org/files/mimic-iv-1.0/hosp/labevents.csv', low_memory=False)
procedures = pd.read_csv('/scratch/fs999/shamoutlab/data/physionet.org/files/mimic-iv-1.0/hosp/procedures_icd.csv', low_memory=False)

In [29]:
patients[patients.subject_id == 19999068]

        subject_id gender  anchor_age  anchor_year anchor_year_group  dod
382275    19999068      M          63         2161       2011 - 2013  NaN

In [30]:
admission[admission.subject_id == 19999068]

,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,marital_status,ethnicity,edregtime,edouttime,hospital_expire_flag
518490,19999068,21606769,2161-08-24 04:10:00,2161-09-02 19:00:00,NaN,EW EMER.,EMERGENCY ROOM,HOME HEALTH CARE,Medicare,ENGLISH,DIVORCED,WHITE,2161-08-24 03:14:00,2161-08-24 05:26:00,0

In [31]:
transfers[transfers.subject_id == 19999068]

,subject_id,hadm_id,transfer_id,eventtype,careunit,intime,outtime
1936697,19999068,21606769.0,32284645,discharge,NaN,2161-09-02 19:06:42,NaN
2035565,19999068,21606769.0,35130402,ED,Emergency Department,2161-08-24 03:14:00,2161-08-24 05:26:00
2035711,19999068,21606769.0,37234188,transfer,Medical/Surgical Intensive Care Unit (MICU/SICU),2161-08-29 08:31:22,2161-08-30 23:48:04
2035773,19999068,21606769.0,38991029,transfer,Med/Surg/GYN,2161-08-30 23:48:04,2161-09-02 19:06:42
2152710,19999068,21606769.0,30143796,admit,Medical/Surgical Intensive Care Unit (MICU/SICU),2161-08-24 05:26:00,2161-08-29 08:31:22

In [37]:
labs[(labs.subject_id == 19999068) & (labs.hadm_id == 21606769.0)]

,labevent_id,subject_id,hadm_id,specimen_id,itemid,charttime,storetime,value,valuenum,valueuom,ref_range_lower,ref_range_upper,flag,priority,comments
100791577,124058101,19999068,21606769.0,55530805,50802,2161-08-24 10:03:00,2161-08-24 10:05:00,-1,-1.00,mEq/L,NaN,NaN,NaN,NaN,NaN
100791578,124058102,19999068,21606769.0,55530805,50804,2161-08-24 10:03:00,2161-08-24 10:05:00,24,24.00,mEq/L,21.00,30.00,NaN,NaN,NaN
100791579,124058104,19999068,21606769.0,55530805,50818,2161-08-24 10:03:00,2161-08-24 10:05:00,38,38.00,mm Hg,35.00,45.00,NaN,NaN,NaN
100791580,124058105,19999068,21606769.0,55530805,50820,2161-08-24 10:03:00,2161-08-24 10:05:00,7.39,7.39,units,7.35,7.45,NaN,NaN,NaN
100791581,124058106,19999068,21606769.0,55530805,50821,2161-08-24 10:03:00,2161-08-24 10:05:00,148,148.00,mm Hg,85.00,105.00,abnormal,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121664701,124058318,19999068,21606769.0,3980150,50920,2161-08-31 06:35:00,2161-08-31 08:28:00,NaN,NaN,NaN,NaN,NaN,NaN,ROUTINE,"Using this patient's age, gender, and serum cr..."
121860974,124058165,19999068,21606769.0,74734534,51006,2161-08-26 04:34:00,2161-08-26 05:46:00,2,2.00,mg/dL,6.00,20.00,abnormal,ROUTINE,VERIFIED BY REPLICATE ANALYSIS.
121860975,124058176,19999068,21606769.0,6336662,51006,2161-08-26 16:20:00,2161-08-26 17:30:00,1,1.00,mg/dL,6.00,20.00,abnormal,STAT,VERIFIED BY REPLICATE ANALYSIS.
121872788,124058147,19999068,21606769.0,53337656,51265,2161-08-26 04:34:00,2161-08-26 05:46:00,90,90.00,K/uL,150.00,440.00,abnormal,ROUTINE,VERIFIED BY SMEAR.
121897945,124058205,19999068,21606769.0,54198400,51266,2161-08-27 01:57:00,2161-08-27 03:16:00,NaN,NaN,NaN,NaN,NaN,NaN,STAT,VERY LOW.

In [42]:
procedures[procedures.subject_id == 19999068]

        subject_id   hadm_id  seq_num   chartdate icd_code  icd_version
719508    19999068  21606769        2  2161-08-25     9671            9
719509    19999068  21606769        1  2161-08-25     9604            9