In [1]:
import os
import optuna
import pandas as pd
from optuna.trial import TrialState
from optuna.study import StudyDirection

In [2]:
pd.set_option('display.precision', 25)

In [12]:
import os
import pandas as pd
import optuna
from optuna.trial import TrialState

def best_trial(
    db_path: str,
    study_name: str,
    n_trials: int = 50,
    direction: str = 'min'
):
    study = optuna.load_study(
        study_name=study_name,
        storage=f"sqlite:///{db_path}"
    )

    first_n = sorted(study.trials, key=lambda t: t.number)[:n_trials]
    completed = [t for t in first_n if t.state == TrialState.COMPLETE]

    if not completed:
        raise ValueError("No completed trials found in the first N trials.")

    if direction == 'min':
        best = min(completed, key=lambda t: t.value)
    elif direction == 'max':
        best = max(completed, key=lambda t: t.value)
    else:
        raise ValueError("Direction must be 'min' or 'max'")

    return {
        'trial_number': best.number,
        'value': best.value,
        'learning_rate': best.params.get('learning_rate'),
        'weight_decay': best.params.get('weight_decay'),
        'pooling': best.params.get('pooling'),
        'use_numeric': best.params.get('use_numeric'),
        'dropout':best.params.get('dropout')
    }

# Loop and collect results
dbs_path = '/scratch/sas10092/ehr-foundation/models/optuna_dbs/'
dbs = os.listdir(dbs_path)

rows = []
for db in dbs:
    arch = db.split('_')[0]
    if arch == 'big':
        arch = 'big_bird'
    task = db[len(arch)+1:-3]

    result = best_trial(
        db_path=os.path.join(dbs_path, db),
        study_name=arch,
        n_trials=25,
        direction='min'
    )
    row = {
        'arch': arch,
        'task': task,
        **result
    }
    rows.append(row)

# Convert to DataFrame and reorder columns
df = pd.DataFrame(rows)
# df = df[['arch', 'task', 'trial_number', 'value', 'learning_rate', 'weight_decay', 'pooling', 'use_numeric','dropout']]

# Optionally save to CSV


# Show result
df = df.sort_values(['task'])
# df = df[df.arch != 'bert']
df = df.reset_index(drop=True)
# df.to_csv("best_trials_summary.csv", index=False)

In [15]:
df#[df.dropout.isna()==False]#.sort_values('arch')

,arch,task,trial_number,value,learning_rate,weight_decay,pooling,use_numeric,dropout
0,bert,behrt_y_icu_readmit_30,24,0.1479659527540206909179688,0.0004410003173006130702122,NaN,None,None,NaN
1,bert,behrt_y_los_7,12,0.2906840443611145019531250,0.0004937993814347803062798,NaN,None,None,NaN
2,bert,behrt_y_mort,18,0.1813116371631622314453125,0.0004461816873784076953671,NaN,None,None,NaN
3,bert,behrt_y_mort_1yr,12,0.2511317431926727294921875,0.0004912898954059036161698,NaN,None,None,NaN
4,remed,bert-ft_y_icu_readmit_30,5,0.1592701822519302368164062,0.0006827342880425098193761,NaN,None,None,NaN
5,descemb,bert-ft_y_icu_readmit_30,9,0.1541414111852645874023438,0.0002796630109406860018213,NaN,None,None,0.1000000000000000055511151
6,genhpf,bert-ft_y_icu_readmit_30,16,0.1495129615068435668945312,0.0000850304259057302704895,NaN,None,None,0.1000000000000000055511151
7,descemb,bert-ft_y_los_7,19,0.2916699051856994628906250,0.0000732437572907189334568,NaN,None,None,0.1000000000000000055511151
8,genhpf,bert-ft_y_los_7,10,0.2927992939949035644531250,0.0000159097362635984281931,NaN,None,None,0.1000000000000000055511151
9,genhpf,bert-ft_y_mort,18,0.1655942052602767944335938,0.0000995249896829537985610,NaN,None,None,0.1000000000000000055511151
10,descemb,bert-ft_y_mort,23,0.1679510772228240966796875,0.0000126803161132836178266,NaN,None,None,0.5000000000000000000000000
11,remed,bert-ft_y_mort,7,0.2209499180316925048828125,0.0002211011424334833523706,NaN,None,None,NaN
12,remed,bert-ft_y_mort_1yr,22,0.2779466509819030761718750,0.0001571722033355856386165,NaN,None,None,NaN
13,genhpf,bert-ft_y_mort_1yr,17,0.2491753399372100830078125,0.0000836443083184374455794,NaN,None,None,0.1000000000000000055511151
14,descemb,bert-ft_y_mort_1yr,15,0.2561964988708496093750000,0.0003264175745067121841951,NaN,None,None,0.5000000000000000000000000
15,bert,cehrbert_y_icu_readmit_30,14,0.1512514352798461914062500,0.0001992065030718885663280,NaN,None,None,NaN
16,bert,cehrbert_y_los_7,22,0.2865801453590393066406250,0.0001969766517022069219484,NaN,None,None,NaN
17,bert,cehrbert_y_mort,19,0.1733195036649703979492188,0.0001974913617976344374846,NaN,None,None,NaN
18,bert,cehrbert_y_mort_1yr,14,0.2493328005075454711914062,0.0001686502925057529697107,NaN,None,None,NaN
19,descemb,cls-ft_y_icu_readmit_30,13,0.1553010195493698120117188,0.0003294440388451785645292,NaN,None,None,0.5000000000000000000000000
20,descemb,cls-ft_y_los_7,14,0.3071016669273376464843750,0.0003319692454709375684964,NaN,None,None,0.3000000000000000444089210
21,descemb,cls-ft_y_mort,4,0.1901640444993972778320312,0.0003055939259689705532995,NaN,None,None,0.3000000000000000444089210
22,descemb,cls-ft_y_mort_1yr,12,0.2575601339340209960937500,0.0004999215308387665659962,NaN,None,None,0.1000000000000000055511151
23,bert,hibehrt_y_icu_readmit_30,12,0.1596442013978958129882812,0.0004926639841371801241399,NaN,None,None,NaN
24,bert,hibehrt_y_los_7,12,0.3179458975791931152343750,0.0004924741293942471766221,NaN,None,None,NaN
25,bert,hibehrt_y_mort,21,0.2070956379175186157226562,0.0004866231754202219607873,NaN,None,None,NaN
26,bert,hibehrt_y_mort_1yr,21,0.2793842256069183349609375,0.0004023888283350409095576,NaN,None,None,NaN
27,remed,hparams-opt_y_los_7,22,0.3272631168365478515625000,0.0004016913131031948740179,NaN,None,None,NaN
28,bert,medbert_y_icu_readmit_30,15,0.1503318697214126586914062,0.0004142171971878185724077,NaN,None,None,NaN
29,bert,medbert_y_los_7,8,0.3050748705863952636718750,0.0004923507733633032072001,NaN,None,None,NaN
30,bert,medbert_y_mort,11,0.1993293911218643188476562,0.0003901667429672213329578,NaN,None,None,NaN
31,bert,medbert_y_mort_1yr,21,0.2552400529384613037109375,0.0004902023154003352098732,NaN,None,None,NaN
32,modernbert,y_icu_readmit_30,24,0.1598976254463195800781250,0.0000496541493420857315590,0.0046004391975919822765917,cls,False,NaN
33,longformer,y_icu_readmit_30,17,0.1505672782659530639648438,0.0000491102283129059573492,0.0031886759370457901097140,mean,False,NaN
34,big_bird,y_icu_readmit_30,3,0.1492381989955902099609375,0.0000428163092923057811835,0.0018808254438205315728361,cls,True,NaN
35,roberta,y_icu_readmit_30,23,0.1502110958099365234375000,0.0000498050113954703573601,0.0052187395231408128040695,cls,False,NaN
36,bert,y_icu_readmit_30,4,0.1527584940195083618164062,0.0000430370924272323866116,0.0067819602994546824767386,mean,True,NaN
37,roformer,y_icu_readmit_30,15,0.1489248424768447875976562,0.0000499514790275800164691,0.0020927920933002898060127,mean,True,NaN
38,roberta,y_los_7,11,0.3000666797161102294921875,0.0000486538307043517519613,0.0010136034211575320994336,mean,True,NaN
39,big_bird,y_los_7,11,0.2804784774780273437500000,0.0000490589387547141041060,0.0011142372924009200096940,cls,False,NaN
40,modernbert,y_los_7,2,0.2859977781772613525390625,0.0000363530193589752407342,0.0074651289474047368213694,cls,False,NaN
41,bert,y_los_7,20,0.3017557561397552490234375,0.0000439664682281120229547,0.0047381922943086282606906,cls,True,NaN
42,longformer,y_los_7,9,0.2929820716381072998046875,0.0000355356285417084922303,0.0016298903184348663072956,mean,False,NaN
43,roformer,y_los_7,15,0.2789000272750854492187500,0.0000447012635919133224254,0.0012935092058895870416324,mean,True,NaN
44,longformer,y_mort,16,0.1828667670488357543945312,0.0000492864162468889283487,0.0038185209096803906375639,mean,False,NaN
45,roberta,y_mort,14,0.1794979721307754516601562,0.0000430787579596155799431,0.0024835244130396900985591,cls,True,NaN
46,modernbert,y_mort,12,0.1677189320325851440429688,0.0000499118596736989372288,0.0028065179169882701649963,mean,True,NaN
47,bert,y_mort,12,0.1827154457569122314453125,0.0000499360211001447748839,0.0015881429643435386860756,cls,False,NaN
48,big_bird,y_mort,1,0.1752811670303344726562500,0.0000394282640136029135310,0.0014311249101715121413714,mean,False,NaN
49,roformer,y_mort,9,0.1697551757097244262695312,0.0000452042995545787226037,0.0010115857964911210628567,cls,True,NaN
50,bert,y_mort_1yr,24,0.2670222818851470947265625,0.0000494107214099990290886,0.0012021417402238328536040,cls,False,NaN
51,modernbert,y_mort_1yr,12,0.2668360769748687744140625,0.0000492322581200942537027,0.0045373516348084595023460,cls,False,NaN
52,roformer,y_mort_1yr,11,0.2468231618404388427734375,0.0000485752213286119608002,0.0011537017023468829415855,mean,False,NaN
53,longformer,y_mort_1yr,13,0.2715175449848175048828125,0.0000484925818207611143890,0.0059281081083298178477370,cls,True,NaN
54,big_bird,y_mort_1yr,2,0.2470655739307403564453125,0.0000422487527308513093082,0.0021682655734662015581393,cls,False,NaN
55,roberta,y_mort_1yr,21,0.2640747725963592529296875,0.0000344480402594291517477,0.0051060732370478379912870,cls,False,NaN

In [11]:
# change this
study = df.iloc[1]
study

arch                     bert
task             behrt_y_mort
trial_number               18
value              0.18131164
learning_rate      0.00044618
weight_decay              NaN
pooling                  None
use_numeric              None
Name: 1, dtype: object

In [12]:
pd.read_csv('best_trials_summary.csv')

,trial_number,value,learning_rate,weight_decay,pooling,use_numeric,task,arch
0,12,0.18271545,0.00004994,0.00158814,cls,False,y_mort,bert
1,17,0.15056728,0.00004911,0.00318868,mean,False,y_icu_readmit_30,longformer
2,12,0.16771893,0.00004991,0.00280652,mean,True,y_mort,modernbert
3,2,0.24706557,0.00004225,0.00216827,cls,False,y_mort_1yr,big_bird
4,11,0.24682316,0.00004858,0.00115370,mean,False,y_mort_1yr,roformer
5,11,0.28047848,0.00004906,0.00111424,cls,False,y_los_7,big_bird
6,16,0.18286677,0.00004929,0.00381852,mean,False,y_mort,longformer
7,2,0.28599778,0.00003635,0.00746513,cls,False,y_los_7,modernbert
8,14,0.17949797,0.00004308,0.00248352,cls,True,y_mort,roberta
9,9,0.29298207,0.00003554,0.00162989,mean,False,y_los_7,longformer
10,24,0.15989763,0.00004965,0.00460044,cls,False,y_icu_readmit_30,modernbert
11,15,0.14892484,0.00004995,0.00209279,mean,True,y_icu_readmit_30,roformer
12,9,0.16975518,0.00004520,0.00101159,cls,True,y_mort,roformer
13,21,0.26407477,0.00003445,0.00510607,cls,False,y_mort_1yr,roberta
14,3,0.14923820,0.00004282,0.00188083,cls,True,y_icu_readmit_30,big_bird
15,23,0.15021110,0.00004981,0.00521874,cls,False,y_icu_readmit_30,roberta
16,20,0.30175576,0.00004397,0.00473819,cls,True,y_los_7,bert
17,4,0.15275849,0.00004304,0.00678196,mean,True,y_icu_readmit_30,bert
18,15,0.27890003,0.00004470,0.00129351,mean,True,y_los_7,roformer
19,24,0.26702228,0.00004941,0.00120214,cls,False,y_mort_1yr,bert
20,12,0.26683608,0.00004923,0.00453735,cls,False,y_mort_1yr,modernbert
21,11,0.30006668,0.00004865,0.00101360,mean,True,y_los_7,roberta
22,13,0.27151754,0.00004849,0.00592811,cls,True,y_mort_1yr,longformer
23,1,0.17528117,0.00003943,0.00143112,mean,False,y_mort,big_bird

In [16]:
import polars as pl
pl.Config.set_tbl_rows(50)
pl.Config.set_fmt_float("full")

polars.config.Config

In [18]:
pl.read_parquet('./downstream_idx.parquet').filter(pl.col('subject_id') == 10003502)#[:,:30]

shape: (1, 54)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ subject_i ┆ hadm_id  ┆ hosp_admi ┆ hosp_disc ┆ … ┆ wStay_sta ┆ wStay_end ┆ wStay_sta ┆ wStay_end │
│ d         ┆ ---      ┆ ssion_tim ┆ harge_tim ┆   ┆ rt_1024   ┆ _1024     ┆ rt_1536   ┆ _1536     │
│ ---       ┆ i64      ┆ e         ┆ e         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ i64       ┆          ┆ ---       ┆ ---       ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64       │
│           ┆          ┆ datetime[ ┆ datetime[ ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ μs]       ┆ μs]       ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10003502  ┆ 29011269 ┆ 2169-08-2 ┆ 2169-08-2 ┆ … ┆ 1145      ┆ 1987      ┆ 1145      ┆ 1987      │
│           ┆          ┆ 6         ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 16:14:00  ┆ 15:20:00  ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘