In [32]:
import polars as pl
from tqdm.notebook import tqdm
from collections import Counter

In [12]:
x = pl.read_parquet('../../EHRSHOT/EHRSHOT_MEDS/data/data.parquet')

In [17]:
(x['subject_id'].unique())

shape: (6_739,)
Series: 'subject_id' [i64]
[
	115967095
	115967096
	115967097
	115967098
	115967099
	…
	121124986
	121124987
	121124988
	121124989
	121124990
]

In [29]:
lens = []
# Added the colon after the closing parenthesis
for i in tqdm(x['subject_id'].unique()):
    lens.append(x.filter(pl.col('subject_id') == i).shape[0])

  0%|          | 0/6739 [00:00<?, ?it/s]

In [47]:
x = 0
for i in tqdm(lens):
    if i >1024:
        x+=1
print(x)

  0%|          | 0/6739 [00:00<?, ?it/s]

4585

In [54]:
a = pl.read_parquet('../../EHRSHOT/meds_omop_ehrshot/data/data_1.parquet')

In [61]:
pl.read_parquet('../../EHRSHOT/')

shape: (95_414, 3)
┌─────────────────────────────────┬─────────────────────────────────┬──────────────────────────┐
│ code                            ┆ description                     ┆ parent_codes             │
│ ---                             ┆ ---                             ┆ ---                      │
│ str                             ┆ str                             ┆ list[str]                │
╞═════════════════════════════════╪═════════════════════════════════╪══════════════════════════╡
│ STANFORD_RACE/Black, Hispanic   ┆ Black, Hispanic                 ┆ ["Race/3"]               │
│ STANFORD_UNIT/ng/mL FEU         ┆ ng/mL FEU                       ┆ ["UCUM/ug{FEU}/mL"]      │
│ STANFORD_UNIT/nmol BCE/L        ┆ nmol BCE/L                      ┆ ["UCUM/nmol{BColl}eq/L"] │
│ STANFORD_UNIT/mg/g (See scan o… ┆ mg/g (See scan or EMR data for… ┆ ["UCUM/mg/g"]            │
│ STANFORD_UNIT//HPF (See scan o… ┆ /HPF (See scan or EMR data for… ┆ ["UCUM//[HPF]"]          │
│ …                               ┆ …                               ┆ …                        │
│ STANFORD_NOTE_CLASS/traditiona… ┆ traditional glucose tolerance … ┆ ["LOINC/28570-0"]        │
│ STANFORD_NOTE_CLASS/erythropoe… ┆ erythropoeitin, serum (010181)… ┆ ["LOINC/28570-0"]        │
│ STANFORD_NOTE_CLASS/cbc/d/plt   ┆ cbc/d/plt                       ┆ ["LOINC/28570-0"]        │
│ STANFORD_MEAS/CLOT RETRACTION   ┆ CLOT RETRACTION                 ┆ ["LOINC/3245-8"]         │
│ STANFORD_NOTE_CLASS/mr wrist w… ┆ mr wrist wo iv contrast right   ┆ ["LOINC/28570-0"]        │
└─────────────────────────────────┴─────────────────────────────────┴──────────────────────────┘

In [57]:
a['subject_id'].unique()

shape: (77,)
Series: 'subject_id' [i64]
[
	115967130
	115967377
	115967387
	115967535
	115967580
	…
	115973466
	115973512
	115973518
	115973527
	115973628
]